#@ load("@ytt:data", "data")

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kapp-on-cluster
  namespace: #@ data.values.namespace
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  suspend: #@ data.values.suspend
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: kapp-on-cluster-sa
          restartPolicy: Never
          containers:
          - name: deploy
            image: ubuntu:xenial
            args:
            - /bin/bash
            - -c
            - |
              set -e -x

              apt-get update
              apt-get -y install wget git

              echo "Installing kapp..."
              wget -O- https://github.com/k14s/kapp/releases/download/v0.4.0/kapp-linux-amd64 > /tmp/kapp
              echo "7a61cf9523281d94711c752ebd8d890068602f3fe6baf344895fbc59b9d5664e  /tmp/kapp" | shasum -c -
              mv /tmp/kapp /usr/local/bin/kapp
              chmod +x /usr/local/bin/kapp
              echo "Installed kapp"

              git clone https://github.com/k14s/kapp
              cd kapp
              kapp --tty --yes app-group -g gitops deploy --directory examples/gitops
