#@ load("@ytt:data", "data")

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kapp-on-cluster
  namespace: #@ data.values.rbac.namespace
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  suspend: #@ data.values.suspend_updates
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: kapp-on-cluster-sa
          restartPolicy: Never
          containers:
          - name: deploy
            image: ubuntu:xenial
            args:
            - /bin/bash
            - -c
            - |
              set -e -x

              apt-get update
              apt-get -y install wget git

              echo "Installing kapp..."
              wget -O- https://github.com/k14s/kapp/releases/download/v0.7.0/kapp-linux-amd64 > /tmp/kapp
              echo "55d247fab5bab8b94b7f00b644a1eebb023d9ed448246c84a8c27a05b35475e8  /tmp/kapp" | shasum -c -
              mv /tmp/kapp /usr/local/bin/kapp
              chmod +x /usr/local/bin/kapp
              echo "Installed kapp"

              echo "Cloning repo..."
              if [ -s /var/git-creds/private.key ]; then
                eval $(ssh-agent)
                ssh-add /var/git-creds/private.key
              fi
              git clone (@= data.values.git_repo.url @) /tmp/git-repo
              cd /tmp/git-repo

              echo "Applying changes..."
              kapp --tty --yes app-group deploy \
                -g (@= data.values.name @) \
                --directory (@= data.values.git_repo.directory @) \
                (@= "" if data.values.rbac.cluster else "--into-ns " + data.values.rbac.namespace @)
              echo "Applied changes"
            volumeMounts:
            - name: git-creds
              mountPath: /var/git-creds
          volumes:
          - name: git-creds
            secret:
              secretName: kapp-on-cluster-git-creds
              items:
              - key: private_key
                path: private.key
                defaultMode: 256
---
apiVersion: v1
kind: Secret
metadata:
  name: kapp-on-cluster-git-creds
  namespace: #@ data.values.rbac.namespace
data:
  private_key: #@ data.values.git_repo.private_key
