#@ load("@ytt:data", "data")

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-on-cluster-sa
  namespace: #@ data.values.rbac.namespace

#@ if not data.values.rbac.custom:
  #@ if data.values.rbac.cluster:

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapp-on-cluster-cl-admin
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
- nonResourceURLs: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kapp-on-cluster-cl-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kapp-on-cluster-cl-admin
subjects:
- kind: ServiceAccount
  name: kapp-on-cluster-sa
  namespace: #@ data.values.rbac.namespace

  #@ else:

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kapp-on-cluster-ns-admin
  namespace: #@ data.values.rbac.namespace
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kapp-on-cluster-ns-admin-binding
  namespace: #@ data.values.rbac.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kapp-on-cluster-ns-admin
subjects:
- kind: ServiceAccount
  name: kapp-on-cluster-sa
  namespace: #@ data.values.rbac.namespace

  #@ end
#@ end
