name: test-gh
on: [push, pull_request]
jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: src/github.com/k14s/kapp
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.0.0-alpha.3
      with:
        cluster_name: kapp
    - name: Run Tests
      run: |
        set -e -x
        export GOPATH=$(echo `pwd`/../../../../)

        # install ytt for build
        mkdir -p tmp-k14s/bin/
        wget -O- https://k14s.io/install.sh | K14SIO_INSTALL_BIN_DIR=tmp-k14s/bin bash
        rm -f tmp-k14s/bin/kapp
        export PATH=`pwd`/tmp-k14s/bin:$PATH

        ./hack/build-binaries.sh

        export KAPP_E2E_NAMESPACE=kapp-test
        kubectl create ns $KAPP_E2E_NAMESPACE
        ./hack/test-all.sh
